# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AUjg_x3Hwt8HkQ5iMVCKV8HsMriOoqcm
"""

import pandas as pd
import numpy as np
import seaborn as sns

game_data = "/content/games_final.csv"

df = pd.read_csv(game_data)

df.head()

# Load the CSV file into a pandas DataFrame
df = pd.read_csv('/content/games_final.csv')

# Define the ranges (bins) you want to group your data into
bins = [4999, 100000, 1000000, 10000000, 100000000, 1000000000, 10000000000]

# Define labels for these ranges
#labels = ['5k-100k', '100k-1M', '1M-10M', '10M-100M', '100M-1B', '1B-10B']
labels = [1, 2, 3, 4, 5, 6]

# Create a new column with categorized data
df['range_group'] = pd.cut(df['Downloads'], bins=bins, labels=labels)

# Save the modified DataFrame to a new CSV file
df.to_csv('grouped_data.csv', index=False)

print("Data has been successfully grouped and saved to 'grouped_data.csv'")

df.head(105)

df.info()

df.to_csv("finalll")